# GitHub Issue Configuration File
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##
blank_issues_enabled: false
contact_links:
  - name: ðŸ“ƒ Documentation
    url: https://OpenDevicePartnership.github.io/patina/
    about: Goals, principles, repo layout, build instructions, and more.
